### ISSUE TITLE
Failed to load the php-getters-setters package

### ISSUE THREAD

**Issue by veloxy** [francodacosta/atom-php-getters-setters#17]
Just updated to latest Atom (0.199.0). Getting the following error:

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [php-getters-setters](https://github.com/francodacosta/atom-php-getters-setters) package, v0.3.0

### Stack Trace

Failed to load the php-getters-setters package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/kevin/.atom/packages/php-getters-setters/lib/ui.view.coffee:4:199)
    at /Users/kevin/.atom/packages/php-getters-setters/lib/ui.view.coffee:9:5
    at Object.<anonymous> (/Users/kevin/.atom/packages/php-getters-setters/lib/ui.view.coffee:133:5)
    at Object.<anonymous> (/Users/kevin/.atom/packages/php-getters-setters/lib/ui.view.coffee:135:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "duotone-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
duotone-dark-syntax, v0.2.0
expand-selection-to-quotes, v0.1.0
file-icons, v1.5.5
one-dark-ui, v0.8.1
php-getters-setters, v0.3.0
php-twig, v3.0.0
sync-settings, v0.2.2
syntax-settings, v0.7.1
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by veloxy** [comment]
Seems to work again after a restart
