### ISSUE TITLE
Uncaught ReferenceError: Workspace is not defined

### ISSUE THREAD

**Issue by vevedh** [francodacosta/atom-php-getters-setters#21]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Unknown Windows Version
**Thrown From**: [php-getters-setters](https://github.com/francodacosta/atom-php-getters-setters) package, v0.5.4

### Stack Trace

Uncaught ReferenceError: Workspace is not defined

```
At C:\Users\THSDCHE\.atom\packages\php-getters-setters\lib\php-getters-setters.coffee:101

ReferenceError: Workspace is not defined
  at Object.module.exports.showUI (C:\Users\THSDCHE\.atom\packages\php-getters-setters\lib\php-getters-setters.coffee:101:18)
  at atom-workspace.atom.commands.add.php-getters-setters:showUI (C:\Users\THSDCHE\.atom\packages\php-getters-setters\lib\php-getters-setters.coffee:61:53)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\THSDCHE\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\THSDCHE\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\THSDCHE\AppData\Local\atom\app-0.210.0\resources\app.asar\src\command-registry.js:153:19)
  at EventEmitter.<anonymous> (C:\Users\THSDCHE\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:03.8.0 php-getters-setters:showUI (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-boilerplate-snippets, v0.3.1
angularjs-styleguide-snippets, v0.7.0
atom-runner, v2.4.1
atom-sync, v0.4.5
color-picker, v2.0.4
minimap, v4.10.0
php-getters-setters, v0.5.4
php-introspector, v1.0.0
remote-atom, v1.2.6
remote-edit, v1.8.2
save-session, v0.15.5

# Dev
No dev packages
```

**Comment by analyticsseo** [comment]
@vevedh thanks

it should be fixed now on version 0.5.5

**Comment by francodacosta** [comment]
@vevedh thanks

it should be fixed now on version 0.5.5
