### ISSUE TITLE
Uncaught TypeError: Cannot read property 'append' of undefined

### ISSUE THREAD

**Issue by ChristopheBoucaut** [francodacosta/atom-php-getters-setters#22]
[Enter steps to reproduce below:]

1. I add a private property by myself
2. I press ctrl+shift+p, select "php getters setters: newproperty"
3. Enter
4. Error message

**Atom Version**: 1.0.2
**System**: Ubuntu 15.04
**Thrown From**: [php-getters-setters](https://github.com/francodacosta/atom-php-getters-setters) package, v0.5.5

### Stack Trace

Uncaught TypeError: Cannot read property 'append' of undefined

```
At /home/username/.atom/packages/php-getters-setters/lib/php-getters-setters.coffee:88

TypeError: Cannot read property 'append' of undefined
  at Object.module.exports.showAddProperty (/home/username/.atom/packages/php-getters-setters/lib/php-getters-setters.coffee:88:27)
  at atom-workspace.atom.commands.add.php-getters-setters:newPropery (/home/username/.atom/packages/php-getters-setters/lib/php-getters-setters.coffee:62:53)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)

```

### Commands

```
     -1:22.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:22.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 20x -1:22 core:move-left (atom-text-editor.editor.is-focused)
     -1:20.7.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -1:19.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:19.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:18.4.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:20.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:18.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.9.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:16.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:10.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:07.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.3.0 php-getters-setters:newPropery (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "monokai"
    ]
  },
  "php-getters-setters": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-jasmine, v0.6.0
atom-material-ui, v0.5.2
autocomplete-phpunit, v1.0.2
docblockr, v0.7.3
file-icons, v1.5.8
highlight-selected, v0.10.1
linter, v1.2.4
linter-jshint, v1.0.5
linter-jsonlint, v0.1.4
linter-php, v0.0.15
linter-phpcs, v1.0.5
monokai, v0.14.0
php-getters-setters, v0.5.5
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by francodacosta** [comment]
The new property is still under development, you should not be able to 
access it

thanks for reporting it


On 16/07/2015 16:16, Christophe Boucaut wrote:
>
> [Enter steps to reproduce below:]
>
>  1. I add a private property by myself
>  2. I press ctrl+shift+p, select "php getters setters: newproperty"
>  3. Enter
>  4. Error message
>
> *Atom Version*: 1.0.2
> *System*: Ubuntu 15.04
> *Thrown From*: php-getters-setters 
> <https://github.com/francodacosta/atom-php-getters-setters> package, 
> v0.5.5
>
>
>       Stack Trace
>
> Uncaught TypeError: Cannot read property 'append' of undefined
>
> |At 
> /home/username/.atom/packages/php-getters-setters/lib/php-getters-setters.coffee:88 
> TypeError: Cannot read property 'append' of undefined at 
> Object.module.exports.showAddProperty 
> (/home/username/.atom/packages/php-getters-setters/lib/php-getters-setters.coffee:88:27) 
> at atom-workspace.atom.commands.add.php-getters-setters:newPropery 
> (/home/username/.atom/packages/php-getters-setters/lib/php-getters-setters.coffee:62:53) 
> at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent 
> (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29) at 
> /usr/share/atom/resources/app.asar/src/command-registry.js:3:61 at 
> CommandPaletteView.module.exports.CommandPaletteView.confirmed 
> (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32) 
> at CommandPaletteView.module.exports.SelectListView.confirmSelection 
> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21) 
> at space-pen-div.atom.commands.add.core:confirm 
> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19) 
> at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent 
> (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29) at 
> /usr/share/atom/resources/app.asar/src/command-registry.js:3:61 at 
> KeymapManager.module.exports.KeymapManager.dispatchCommandEvent 
> (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16) 
> |
>
>
>       Commands
>
> |-1:22.3.0 core:move-down (atom-text-editor.editor.is-focused) 
> -1:22.1.0 editor:move-to-end-of-screen-line 
> (atom-text-editor.editor.is-focused) 20x -1:22 core:move-left 
> (atom-text-editor.editor.is-focused) -1:20.7.0 
> find-and-replace:select-next (atom-text-editor.editor.is-focused) 
> -1:19.3.0 editor:move-to-end-of-screen-line 
> (atom-text-editor.editor.is-focused.autocomplete-active) 3x -1:19.1.0 
> core:move-left (atom-text-editor.editor.is-focused) -1:18.4.0 
> find-and-replace:select-next (atom-text-editor.editor.is-focused) 
> -0:21.2.0 core:copy (atom-text-editor.editor.is-focused) -0:20.9.0 
> core:close (atom-text-editor.editor.is-focused) -0:19.2.0 core:paste 
> (atom-text-editor.editor.is-focused) -0:18.9.0 core:save 
> (atom-text-editor.editor.is-focused) -0:16.9.0 
> linter:set-bubble-transparent (atom-text-editor.editor.is-focused) 
> -0:16.4.0 command-palette:toggle (atom-text-editor.editor.is-focused) 
> 3x -0:10.4.0 core:move-down (atom-text-editor.editor.mini.is-focused) 
> -0:07.3.0 core:confirm (atom-text-editor.editor.mini.is-focused) 
> -0:07.3.0 php-getters-setters:newPropery (atom-text-editor.editor) |
>
>
>       Config
>
> {
>    "core": {
>      "themes": [
>        "atom-material-ui",
>        "monokai"
>      ]
>    },
>    "php-getters-setters": {}
> }
>
>
>       Installed Packages
>
> # User
> angularjs, v0.3.0
> atom-jasmine, v0.6.0
> atom-material-ui, v0.5.2
> autocomplete-phpunit, v1.0.2
> docblockr, v0.7.3
> file-icons, v1.5.8
> highlight-selected, v0.10.1
> linter, v1.2.4
> linter-jshint, v1.0.5
> linter-jsonlint, v0.1.4
> linter-php, v0.0.15
> linter-phpcs, v1.0.5
> monokai, v0.14.0
> php-getters-setters, v0.5.5
> project-manager, v1.15.11
>
> # Dev
> No dev packages
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/francodacosta/atom-php-getters-setters/issues/22>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by ChristopheBoucaut** [comment]
Okey :) nice work for the rest of the plugin ;)
